import type {Metadata} from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Base",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja" suppressHydrationWarning={true}>
        <body suppressHydrationWarning={true}>
            {children}
        </body>
        </html>
    );
}
