import type {Metadata} from "next";
import "./globals.css";
import StoreProvider from "@/stores";

export const metadata: Metadata = {
    title: "Base",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja" suppressHydrationWarning={true}>
        <body suppressHydrationWarning={true}>
            <StoreProvider lastUpdate={new Date().getTime()}>
                {children}
            </StoreProvider>
        </body>
        </html>
    );
}
